# Use Node.js 20 (latest LTS as of a likely point)
FROM node:20-buster-slim

# Copy Dir
COPY . ./app

# Work to Dir
WORKDIR /app

# Install Node Package
RUN npm install --legacy-peer-deps

# Set Env
ENV NODE_ENV staging

EXPOSE 8571

# Cmd script
CMD ["npm", "run", "start"]